version: "3.4"
name: Supermercado-local-test-env
services:
  database:
    image: mariadb:11
    container_name: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - network1
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  tomcat:
    image: tomcat:9.0.88-jdk17-openjdk-slim
    container_name: tomcat
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - network1
    volumes:
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./target/supermercado:/usr/local/tomcat/webapps/supermercado
      - ./images:/usr/local/tomcat/webapps/supermercado
      - ./logs:/usr/local/tomcat/logs
volumes:
  db:
networks:
  network1:
    driver: bridge