CREATE DATABASE IF NOT EXISTS test;
GRANT ALL PRIVILEGES ON test.* TO test;
USE test;

CREATE TABLE IF NOT EXISTS PRODUCTOS (
    PRODUCTO_ID INT PRIMARY KEY,
    NOMBRE VARCHAR(50),
    PRECIO DECIMAL(10,2),
    FILENAME VARCHAR(100),
    CATEGORIA VARCHAR(50),
    EXISTENCIAS INT
);

INSERT INTO PRODUCTOS (PRODUCTO_ID, NOMBRE, PRECIO, CATEGORIA, EXISTENCIAS) VALUES (1, 'Poke Ball', 10.99, 'Objetos de captura', 100);


CREATE TABLE IF NOT EXISTS CLIENTES (
    ALIAS_CLIENTE VARCHAR(20) PRIMARY KEY,
    CONTRASEÑA VARCHAR(50),
    DIRECCION VARCHAR(100),
    TELEFONO VARCHAR(15),
    ROLE VARCHAR(20) DEFAULT 'user'
);

INSERT INTO CLIENTES (ALIAS_CLIENTE, CONTRASEÑA, DIRECCIÓN, TELEFONO, ROLE) VALUES ('jorge', SHA1('jorge'), 'lacalle', 123-2333, 'admin');
INSERT INTO CLIENTES (ALIAS_CLIENTE, CONTRASEÑA, DIRECCIÓN, TELEFONO, ROLE) VALUES ('user', SHA1('user'), 'lacalle', 123-2333, 'user');
